In [1]:
import pandas as pd

In [2]:

# Creating a new DataFrame with the selected columns
df = pd.read_csv('./data/finalTrain.csv')

In [3]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41

In [4]:
len(df)

45584

In [5]:
import numpy as np
# Set the earth's radius (in kilometers)
R = 6371

# Convert degrees to radians
def deg_to_rad(degrees):
    return degrees * (np.pi/180)

# Function to calculate the distance between two points using the haversine formula
def distcalculate(lat1, lon1, lat2, lon2):
    d_lat = deg_to_rad(lat2-lat1)
    d_lon = deg_to_rad(lon2-lon1)
    a = np.sin(d_lat/2)**2 + np.cos(deg_to_rad(lat1)) * np.cos(deg_to_rad(lat2)) * np.sin(d_lon/2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1-a))
    return R * c
  
# Calculate the distance between each pair of points
df['distance'] = np.nan

for i in range(len(df)):
    df.loc[i, 'distance'] = distcalculate(df.loc[i, 'Restaurant_latitude'], 
                                        df.loc[i, 'Restaurant_longitude'], 
                                        df.loc[i, 'Delivery_location_latitude'], 
                                        df.loc[i, 'Delivery_location_longitude'])

In [6]:
df.to_csv("./data/finalTrain_new.csv",index=False)

In [7]:
#As per selected column form feature selection
selected_columns = ['Delivery_person_Age',
    'Delivery_person_Ratings',
    'Restaurant_latitude',
    'Restaurant_longitude',
    'Delivery_location_latitude',
    'Delivery_location_longitude',
    'Weather_conditions',
    'multiple_deliveries',
    'Festival',
    'City',
    'Road_traffic_density',
    'Vehicle_condition',
    'Type_of_vehicle',
    'distance',
    'Time_taken (min)'
    ]

In [8]:
# Creating a new DataFrame with the selected columns
import pandas as pd
df = pd.read_csv('./data/finalTrain_new.csv')

In [9]:
df = df[selected_columns]

In [10]:
df.to_csv("./data/finalTrain_new.csv",index=False)

In [11]:
df

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Weather_conditions,multiple_deliveries,Festival,City,Road_traffic_density,Vehicle_condition,Type_of_vehicle,distance,Time_taken (min)
0,36.0,4.2,30.327968,78.046106,30.397968,78.116106,Fog,3.0,No,Metropolitian,Jam,2,motorcycle,10.280582,46
1,21.0,4.7,10.003064,76.307589,10.043064,76.347589,Stormy,1.0,No,Metropolitian,High,1,motorcycle,6.242319,23
2,23.0,4.7,18.562450,73.916619,18.652450,74.006619,Sandstorms,1.0,No,Metropolitian,Medium,1,scooter,13.787860,21
3,34.0,4.3,30.899584,75.809346,30.919584,75.829346,Sandstorms,0.0,No,Metropolitian,Low,0,motorcycle,2.930258,20
4,24.0,4.7,26.463504,80.372929,26.593504,80.502929,Fog,1.0,No,Metropolitian,Jam,1,scooter,19.396618,41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45579,30.0,4.8,26.902328,75.794257,26.912328,75.804257,Windy,0.0,No,Metropolitian,High,1,motorcycle,1.489846,32
45580,21.0,4.6,0.000000,0.000000,0.070000,0.070000,Windy,1.0,No,Metropolitian,Jam,0,motorcycle,11.007735,36
45581,30.0,4.9,13.022394,80.242439,13.052394,80.272439,Cloudy,0.0,No,Metropolitian,Low,1,scooter,4.657195,16
45582,20.0,4.7,11.001753,76.986241,11.041753,77.026241,Cloudy,1.0,No,Metropolitian,High,0,motorcycle,6.232393,26
45583,23.0,4.9,23.351058,85.325731,23.431058,85.405731,Fog,1.0,No,Metropolitian,Medium,2,scooter,12.074396,36

In [11]:
#Independent and Dependent features
X = df.drop(labels=['Time_taken (min)'],axis=1)
Y = df[['Time_taken (min)']]

In [12]:
X.head()

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Weather_conditions,multiple_deliveries,Festival,City,Road_traffic_density,Vehicle_condition,Type_of_vehicle,distance
0,36.0,4.2,30.327968,78.046106,30.397968,78.116106,Fog,3.0,No,Metropolitian,Jam,2,motorcycle,10.280582
1,21.0,4.7,10.003064,76.307589,10.043064,76.347589,Stormy,1.0,No,Metropolitian,High,1,motorcycle,6.242319
2,23.0,4.7,18.562450,73.916619,18.652450,74.006619,Sandstorms,1.0,No,Metropolitian,Medium,1,scooter,13.787860
3,34.0,4.3,30.899584,75.809346,30.919584,75.829346,Sandstorms,0.0,No,Metropolitian,Low,0,motorcycle,2.930258
4,24.0,4.7,26.463504,80.372929,26.593504,80.502929,Fog,1.0,No,Metropolitian,Jam,1,scooter,19.396618

In [13]:
Y.head()

   Time_taken (min)
0                46
1                23
2                21
3                20
4                41

In [14]:
# Define which columns should be ordinal-encoded and which should be scaled
categorical_cols = X.select_dtypes(include='object').columns
numerical_cols = X.select_dtypes(exclude='object').columns

In [15]:
categorical_cols

Index(['Weather_conditions', 'Festival', 'City', 'Road_traffic_density',
       'Type_of_vehicle'],
      dtype='object')

In [16]:
numerical_cols

Index(['Delivery_person_Age', 'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'multiple_deliveries',
       'Vehicle_condition', 'distance'],
      dtype='object')

In [17]:
df['Festival'].unique()

array(['No', 'Yes', nan], dtype=object)

In [18]:
df['Road_traffic_density'].unique()

array(['Jam', 'High', 'Medium', 'Low', nan], dtype=object)

In [19]:
df['Type_of_vehicle'].unique()

array(['motorcycle', 'scooter', 'electric_scooter', 'bicycle'],
      dtype=object)

In [20]:
df['Weather_conditions'].unique()

array(['Fog', 'Stormy', 'Sandstorms', 'Windy', 'Cloudy', 'Sunny', nan],
      dtype=object)

In [21]:
df['City'].unique()

array(['Metropolitian', 'Urban', 'Semi-Urban', nan], dtype=object)

In [22]:
numerical_cols = ['Delivery_person_Age', 'Delivery_person_Ratings', 'Restaurant_latitude',
                  'Restaurant_longitude', 'Delivery_location_latitude', 'Delivery_location_longitude', 
                  'multiple_deliveries', 'Vehicle_condition', 'distance']
Festival_categories = ['No', 'Yes']
Road_traffic_density_categories = ['Low','Medium','High','Jam']
Type_of_vehicle_categories = ['motorcycle', 'scooter', 'electric_scooter', 'bicycle']
Types_of_City = ['Metropolitian', 'Urban', 'Semi-Urban']
Type_of_Weather_Codition = ['Fog', 'Stormy', 'Sandstorms', 'Windy', 'Cloudy', 'Sunny']

In [23]:
from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
##pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [24]:
# Define the preprocessing for each type of feature
ordinal_encoded_features = ['Festival', 'Road_traffic_density','City']
one_hot_encoded_features = ['Type_of_vehicle','Weather_conditions']
ordinal_categories = [Festival_categories, Road_traffic_density_categories, Types_of_City]

# Numerical Pipeline
num_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

# Ordinal Encoded Pipeline
ordinal_encoded_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ("Ordinal_encoder", OrdinalEncoder(categories=ordinal_categories)),
    ('scaler', StandardScaler())
])

# One-Hot Encoded Pipeline
one_hot_encoded_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder())
])

# Combined Preprocessor
preprocessor = ColumnTransformer(
    transformers=[
    ('num_pipeline', num_pipeline, numerical_cols),
    ('label_encoded_pipeline', ordinal_encoded_pipeline, ordinal_encoded_features),
    ('one_hot_encoded_pipeline', one_hot_encoded_pipeline, one_hot_encoded_features)
    ])

In [25]:
# Train-test split
X = df.drop('Time_taken (min)', axis=1)
y = df['Time_taken (min)']

In [26]:
# Train-test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.30, random_state=30)

In [27]:
X_train.columns

Index(['Delivery_person_Age', 'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Weather_conditions',
       'multiple_deliveries', 'Festival', 'City', 'Road_traffic_density',
       'Vehicle_condition', 'Type_of_vehicle', 'distance'],
      dtype='object')

In [28]:
# Apply the preprocessor to the training data
X_train_transformed=pd.DataFrame(preprocessor.fit_transform(X_train))
X_test_transformed=pd.DataFrame(preprocessor.transform(X_test))

In [29]:
X_train_transformed

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,1.127029,-1.616208e+00,0.647373,0.131167,0.669961,0.116679,-1.311196,-1.223528,-0.079476,-0.142953,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,-0.103625,-3.137140e+00,0.647397,0.131248,0.668629,0.116295,3.962093,-1.223528,-0.080867,6.995304,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.247990,5.130963e-01,1.156141,0.443938,1.228657,0.452410,0.446567,1.160323,-0.086475,-0.142953,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.599606,-1.312022e+00,-0.226656,0.165206,-0.293358,0.156297,0.446567,1.160323,-0.070761,-0.142953,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.775414,-1.616208e+00,0.258322,0.116402,0.230746,0.098366,0.446567,-1.223528,-0.086406,-0.142953,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31903,1.302837,8.172826e-01,1.156298,0.443508,1.228832,0.451945,-1.311196,-0.031602,-0.086475,-0.142953,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
31904,-0.279433,8.172826e-01,0.051172,0.358934,0.004577,0.361939,-1.311196,1.160323,-0.082157,-0.142953,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
31905,-1.685894,-2.701717e-15,0.672333,0.794024,0.699062,0.833653,0.446567,1.160323,-0.078092,-0.142953,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
31906,0.775414,-9.527638e-02,-0.493985,0.326079,-0.605431,0.325013,0.000000,-0.031602,-0.086364,-0.142953,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
31907,-1.334279,2.089099e-01,-0.483196,0.440083,-0.589364,0.449655,0.446567,-1.223528,-0.082086,-0.142953,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [30]:
# Dynamically generate column names for one-hot encoded features
onehot_encoded_features = preprocessor.named_transformers_['one_hot_encoded_pipeline']['onehot'].categories_
onehot_encoded_columns = []

for feature, categories in zip(one_hot_encoded_features, onehot_encoded_features):
    for category in categories:
        onehot_encoded_columns.append(f"{feature}_{category}")

# Combine all column names
columns = numerical_cols + ordinal_encoded_features + onehot_encoded_columns

In [31]:
X_train_transformed.columns = columns
X_test_transformed.columns = columns

In [32]:
X_train_transformed

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,multiple_deliveries,Vehicle_condition,distance,Festival,...,Type_of_vehicle_bicycle,Type_of_vehicle_electric_scooter,Type_of_vehicle_motorcycle,Type_of_vehicle_scooter,Weather_conditions_Cloudy,Weather_conditions_Fog,Weather_conditions_Sandstorms,Weather_conditions_Stormy,Weather_conditions_Sunny,Weather_conditions_Windy
0,1.127029,-1.616208e+00,0.647373,0.131167,0.669961,0.116679,-1.311196,-1.223528,-0.079476,-0.142953,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,-0.103625,-3.137140e+00,0.647397,0.131248,0.668629,0.116295,3.962093,-1.223528,-0.080867,6.995304,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.247990,5.130963e-01,1.156141,0.443938,1.228657,0.452410,0.446567,1.160323,-0.086475,-0.142953,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.599606,-1.312022e+00,-0.226656,0.165206,-0.293358,0.156297,0.446567,1.160323,-0.070761,-0.142953,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.775414,-1.616208e+00,0.258322,0.116402,0.230746,0.098366,0.446567,-1.223528,-0.086406,-0.142953,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31903,1.302837,8.172826e-01,1.156298,0.443508,1.228832,0.451945,-1.311196,-0.031602,-0.086475,-0.142953,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
31904,-0.279433,8.172826e-01,0.051172,0.358934,0.004577,0.361939,-1.311196,1.160323,-0.082157,-0.142953,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
31905,-1.685894,-2.701717e-15,0.672333,0.794024,0.699062,0.833653,0.446567,1.160323,-0.078092,-0.142953,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
31906,0.775414,-9.527638e-02,-0.493985,0.326079,-0.605431,0.325013,0.000000,-0.031602,-0.086364,-0.142953,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
31907,-1.334279,2.089099e-01,-0.483196,0.440083,-0.589364,0.449655,0.446567,-1.223528,-0.082086,-0.142953,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [33]:
X_test_transformed

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,multiple_deliveries,Vehicle_condition,distance,Festival,...,Type_of_vehicle_bicycle,Type_of_vehicle_electric_scooter,Type_of_vehicle_motorcycle,Type_of_vehicle_scooter,Weather_conditions_Cloudy,Weather_conditions_Fog,Weather_conditions_Sandstorms,Weather_conditions_Stormy,Weather_conditions_Sunny,Weather_conditions_Windy
0,7.218275e-02,5.130963e-01,-0.493715,0.324443,-0.590190,0.328421,0.446567,-0.031602,-0.070675,-0.142953,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1,-9.826634e-01,1.121469e+00,1.209883,0.245853,1.293823,0.240176,0.446567,-1.223528,-0.081005,-0.142953,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,-2.794326e-01,-9.527638e-02,0.702518,0.249476,0.739403,0.247387,-1.311196,1.160323,-0.071155,-0.142953,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,-6.310480e-01,-3.994627e-01,0.258322,0.116402,0.234820,0.099778,-1.311196,-0.031602,-0.082190,-0.142953,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,-6.245944e-16,-2.701717e-15,0.701106,0.250194,0.729684,0.245339,0.446567,1.160323,-0.079490,-0.142953,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13671,2.479904e-01,-3.137140e+00,-2.078972,-3.054586,-2.360326,-3.326904,2.204330,1.160323,-0.079103,-0.142953,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
13672,7.754135e-01,-3.994627e-01,0.050114,0.361078,0.002043,0.363785,-1.311196,1.160323,-0.083569,-0.142953,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
13673,-8.068557e-01,2.089099e-01,0.348792,0.224769,0.335376,0.216915,0.446567,-0.031602,-0.082205,-0.142953,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
13674,-8.068557e-01,5.130963e-01,-0.572967,0.281687,-0.680994,0.281263,0.446567,-0.031602,-0.073508,-0.142953,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
13675,-1.036249e-01,5.130963e-01,-0.496477,0.328414,-0.604126,0.328949,-1.311196,1.160323,-0.082085,-0.142953,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [34]:
##Model Trainig
from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [35]:
regression = LinearRegression()
regression.fit(X_train_transformed,y_train)

LinearRegression()

In [36]:
regression.coef_

array([[ 2.2775964 , -2.39798021,  0.01989942, -0.39023666,  0.02754923,
         0.36415023,  1.95156893, -1.77332642, -0.01370187,  1.49707007,
         3.24560453, -0.68228215,  0.98577496,  0.12161522, -0.28327896,
        -0.82411123,  2.37248273,  2.55901201, -0.43599479, -0.38565174,
        -3.8581623 , -0.25168592]])

In [37]:
regression.intercept_

array([26.68327696])

In [38]:
import numpy as np
def evaluate_model(true,predicate):
    mae = mean_absolute_error(true,predicate)
    mse = mean_squared_error(true,predicate)
    rmse = np.sqrt(mean_squared_error(true,predicate))
    r2_square = r2_score(true,predicate)
    return mae,rmse,r2_square

In [39]:
#Train multiple models
models = {
    'LinearRegression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'ElasticNet':ElasticNet()
}

trained_model_list = []
model_list = []
r2_list = []

for i in range(len(list(models))):
    model = list(models.values())[i]
    print("Model is :",model)
    model.fit(X_train_transformed,y_train)

    #make prediction
    y_pred = model.predict(X_test_transformed)
    #print("This is y_pre sum",np.sum(y_pred))
    #print("This is y_test ",y_test[:5])


    mae, rmse ,r2_square=evaluate_model(y_test,y_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model Training Performance')
    print("RMSE:",rmse)
    print("MAE:",mae)
    print("R2 score",r2_square*100)

    r2_list.append(r2_square)
    
    print('='*35)
    print('\n')

Model is : LinearRegression()
LinearRegression
Model Training Performance
RMSE: 6.420775093143964
MAE: 5.094116305251982
R2 score 52.33667511676017
===================================


Model is : Lasso()
Lasso
Model Training Performance
RMSE: 7.100402796671775
MAE: 5.6521222391245365
R2 score 41.712504924424685
===================================


Model is : Ridge()
Ridge
Model Training Performance
RMSE: 6.4207895448839
MAE: 5.094129736295994
R2 score 52.336460557383504
===================================


Model is : ElasticNet()
ElasticNet
Model Training Performance
RMSE: 7.169532709170707
MAE: 5.723221158265725
R2 score 40.571999286550586
===================================

In [40]:
regression.score(X_train_transformed,y_train)

0.5398245817442352

In [41]:
regression.score(X_test_transformed,y_test)

0.5233667511676017